### ISSUE TITLE
The title of the application appears behind the dock

### ISSUE THREAD

**Issue by fsvh** [ozonos/atom-dock#18]
The problem is when I have a window open and the dock is hidden. At the moment I under the mouse to the dock appears, the title of the application appears behind the dock.

Here you have a screenshot and a video if you don't understand what I mean.

![capture d cran de 2014-04-14 15 38 27](https://cloud.githubusercontent.com/assets/5596229/2695816/496eb798-c3db-11e3-949c-06d81d2c11fd.png)

Video
https://plus.google.com/116118568744093631670/posts/gswYTUxWVrX

Thanks! :)

**Comment by cldx** [comment]
I guess this can also be closed?
