### ISSUE TITLE
Dock goes behind windows when switching workspace

### ISSUE THREAD

**Issue by kyuucr** [ozonos/atom-dock#25]
Steps to reproduce:

1. On Gnome 3.12
2. Open a maximized window
3. Switch to new blank workspace using shortcut (Ctrl+Alt+Down)
4. Switch back to the first workspace using shortcut
5. Dock is not appearing when hovered

Another same steps (switch workspace to new one and back) using normal window, I found out that the dock is going behind the window:
![screenshot from 2014-04-22 07 45 36](https://cloud.githubusercontent.com/assets/749098/2760151/2618d290-c9af-11e3-8781-4ce4d255bd6a.png)

I suspect the cause is the usage of global window group from #22 merge

**Comment by cldx** [comment]
Is this still a thing?

**Comment by cldx** [comment]
I can't reproduce it either, since the restacking was removed in 5bff20adb1fa09f998e21a54e76c268ffc9fb6ed i guess we can safely say that if it caused this, it will be gone now.
