### ISSUE TITLE
dock behind LO

### ISSUE THREAD

**Issue by NexuS-Pt** [ozonos/atom-dock#29]
problem in dock with LibreOffice open, the dock stay behind

![screenshot](http://i.imgur.com/V5mQ8Yz.png)

**Comment by cldx** [comment]
Can't reproduce using 3.14. Still relevant?

**Comment by NexuS-Pt** [comment]
I'm using Ubuntu Gnome, and I don't have Gnome 3.14, onlu 2.12

**Comment by cldx** [comment]
Are you sure it's really only Libre Office?

**Comment by cldx** [comment]
Please check if this still happens with the latest commit 5bff20adb1fa09f998e21a54e76c268ffc9fb6ed

**Comment by NexuS-Pt** [comment]
Problem solved :D
