### ISSUE TITLE
Click to minimize

### ISSUE THREAD

**Issue by kaidesu** [ozonos/atom-dock#30]
This is a suggestion, but it would be nice to be able to click to minimize applications from the dock.

My instinct when switching windows is to go straight to the dock. At the moment I'm having to first navigate around the desktop clicking the minimize buttons to clean up my workspace, then going to the dock to pull up the window I wish to see.

**Comment by me4oslav** [comment]
Not happening. The reason it is not happening is this actually rather simple- at computers we work with opened windows and there is absolute no need for you go clean up your workspace. Cleaned up workspace means going back to looking at your wallpaper and that as you can imagine is not really productive at all. :)
Currently flicking on dock icon will show all the opened windows of the application icon you've clicked upon. For example if you have 3 file manager windows and you click on either of the file manager icon on the dock they will just jump in front of whatever windows you have above them and that happens with a single click, which is much easier than minimising all the windows you have above those three file manager windows.
Closing this issue no.

**Comment by kaidesu** [comment]
Thanks for taking the time to reply!

I've also recently come across the Gnome shortcut **CTRL + ALT + D** that will minimize all windows - that does exactly what I wanted; quicker than clicking through each window.

**Comment by me4oslav** [comment]
Always happy to elaborate. :)
