### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by TaylanTatli** [ozonos/atom-dock#31]
Is it possible to reduce icon size?

**Comment by cldx** [comment]
Personally, i would love to make my Icons a static size sometimes, the resizing is making me uncomfortable. But which Icon SIze to choose? 

But i'd love to hear more opinions.

**Comment by me4oslav** [comment]
I like the way it currently works - it automagically detects the best icon size for your resolution and amount of icons displayed on the dock. Is the reasoning for the issue "Because I want choice" rather than some design reason? If there is a design reason behind this request - write it down. Because right no I don't see one.

**Comment by cldx** [comment]
Just to be clear, i was talking about a static size, meaning the Dock Icons would ideally always be the same size as the Launcher Icons. And that's totally my personal opinion. But i'm the kind of person that doesn't have 30 Icons in the Dock, so i wouldn't run into trouble with static sizes.

As for customizable Icon Sizes, i don't think we should do it either, we'd just be busy working against problems that the Gnome Team already found solid solutions for.

**Comment by me4oslav** [comment]
So by "customisable" you mean two options:
A) Current behaviour that is just like Gnome's dock one
B) A behaviour in which launcher and dock icons are both X sized
Did I get it correct?

**Comment by cldx** [comment]
What the OP probably meant is flexible icon sizes to pick from the Extension Settings. But like i said, it's only gonna make us run into more problems, cause if you have f.e. really big Icons, it will run out of space OR it will resize them again, which is pretty much the behavior it has anyways.

So i gues we can close this, cause like you said, the Gnome behavior is actually really good and makes sense. Forget my wishful thinking :)

**Comment by me4oslav** [comment]
Closing, then.
