### ISSUE TITLE
Dock doens't hide if notification panel opened

### ISSUE THREAD

**Issue by Foggalong** [ozonos/atom-dock#36]
To replicate:

1. Full screen window
2. Drag mouse to bottom to trigger notification panel
3. Click back near top of screen
4. Dock now doesn't hide until clicked

**Comment by cldx** [comment]
The Dock should now hide if the MessageTray is openened no matter what. I admit it's not the most beautiful thing but it's okay until MessageTray will die anyways, see commit 5bff20adb1fa09f998e21a54e76c268ffc9fb6ed

**Comment by Foggalong** [comment]
They're killing message tray?! O.o but where will the tay icons go?

**Comment by cldx** [comment]
If i understood correctly, Notifications will go in the Calendar Panel and Legacy Tray Symbols will get disabled until a better implementation is in place.

**Comment by cldx** [comment]
https://wiki.gnome.org/Design/OS/Notifications/Redux

Kinda like this, details might change though.

**Comment by Foggalong** [comment]
Ooo, I like that idea. Looks quite neat too.

Sad about tray symbols though :(
