### ISSUE TITLE
Using the Dock with the new App "Swarm" Animation looks crap

### ISSUE THREAD

**Issue by cldx** [ozonos/atom-dock#39]
Cause obviously the Animation starts out of thin Air. Maybe there's a simple way to change the origin point of the Animation and always tie it to the position of OUR dock button.

**Comment by me4oslav** [comment]
100% agreed. Can somebody fix it?

**Comment by cldx** [comment]
I will try, but i first have to checkout the swarm code cause i never looked how they implemented it.

**Comment by me4oslav** [comment]
It is in JS files, btw and not in the CSS.

**Comment by cldx** [comment]
I tweaked this to a point where the Apps will swarm into view from the center of the screen, which is not quite what i wanted but it's looking much more sophisticated than the apps coming from a seemingly random spot on the side.

I can't commit it right now though since i'm at work :)

**Comment by me4oslav** [comment]
Will take that over the current jumping from stargate behaviour anyday. :)

**Comment by micheleg** [comment]
Have a look at this https://github.com/micheleg/dash-to-dock/commit/6e54659aee6dd8946fa50bb426c64e9bbdd16f4f. Or alternatively overwrite Overview.getShowAppsButton().

**Comment by cldx** [comment]
@micheleg thanks so much, i'm a little retarded cause i was looking at it from the launcher side of things and overwrote _doSpringAnimation

**Comment by cldx** [comment]
If you find the time test this from commit f442db018b1108528460bc4c0f4d8eaa5a4d9032 and tell me if it works for you as well.

(Note to self: Use branches before pushing to master stupid)

**Comment by me4oslav** [comment]
@cldx Why does it come from the bottom left corner? :o

**Comment by cldx** [comment]
I don't know? Have you done 'make install' again and restarted shell?

**Comment by cldx** [comment]
Everthing is cream and sugar.
