### ISSUE TITLE
Extension is not listed in available extensions after install

### ISSUE THREAD

**Issue by arayaq** [ozonos/atom-dock#42]
After cloning and installing, the extension is not listed in the available extensions. Tested with Gnome Tweak Tool and [Gnome website](https://extensions.gnome.org/local/).  Gnome 3.14/Fedora 21.

**Comment by tomvanderlee** [comment]
Did you restart gnome-shell?

**Comment by loctauxphilippe** [comment]
If you want to restart it, Alt+F2, than type "r" (without the quotes)
And it should be into tweak-tool

**Comment by cldx** [comment]
For the fun of it try uninstalling an extension via the makefile, it will still run until restart cause it's in the session. And that's where GTT gets it's info from if i recall correctly.

**Comment by me4oslav** [comment]
Aye, restart the GS.

**Comment by arayaq** [comment]
Logged off and problem persisted. Uninstalled and reinstalled, rebooted and now it workes. Now I am not sure this is an isolated case. I guess this can be closed now.
