### ISSUE TITLE
Dock doesn't disable itself after turning it off

### ISSUE THREAD

**Issue by arayaq** [ozonos/atom-dock#43]
Steps to reproduce:
1. Make sure the extension is disabled.
2. From Gnome Tweak Tool, turn it on.
At this point, the extension will be visible until you hover over it.
3. Turn it off without hovering over the extension.

After that, the extension can't be disabled. Now, if you close GTT and reopen again a message saying the extension can't be loaded is shown.
![](https://cloud.githubusercontent.com/assets/1882727/6398352/9ea86c52-bdb0-11e4-9a7d-f1e8b67e8117.png)

Here the dock is on even if the extension was turned off in GTT

![selection_001](https://cloud.githubusercontent.com/assets/1882727/6398388/d9b31f18-bdb0-11e4-8a4c-99f37d8a8a91.png)

**Comment by me4oslav** [comment]
Is this 3.14?

**Comment by arayaq** [comment]
Yes, Fedora 21 up to date.

**Comment by arayaq** [comment]
Same issue on Gnome 3.12/Ubuntu Gnome.

**Comment by me4oslav** [comment]
Weird, I don't experience it. Can somebody reproduce this?

**Comment by cldx** [comment]
Should work now, i had a hickup in the disable function.

**Comment by kyuucr** [comment]
Fix confirmed on 3.12

**Comment by cldx** [comment]
I can confirm for 3.14 so i guess we can close this.
