### ISSUE TITLE
Dock Icons and open programs indicators disappear.

### ISSUE THREAD

**Issue by athordan** [ozonos/atom-dock#47]
When u use multiple workspaces, like chrome on one, steam and disks on the other, the indicators or icons disappear when you are not on the workspace where the programs are running. if the program is not pinned to the dock, it disappears from the dock as long as I am on the other workspace.

**Comment by tomvanderlee** [comment]
This is the desired behaviour for the the dock according to the design specifications.

**Comment by athordan** [comment]
oh ok thnx

2015-03-10 22:17 GMT+01:00, Tom van der Lee <notifications@github.com>:
