### ISSUE TITLE
Compatibility with GNOME Shell 3.15.91

### ISSUE THREAD

**Issue by marko-lazic** [ozonos/atom-dock#52]
Hi,

I'm sad to say that all of your Extensions do not support gnome shell from staging repos. Also i'm having 'Remove' button disabled, it may have to do with me executing 'sudo make install'.

;-),
Marko

**Comment by cldx** [comment]
That's cause we never tested any of the Extensions against 3.16 so far and none of the metadata is updated.

You can always get rid of the extensions doing a make uninstall (or should be, i can't guarantee cause i didn't get around to check all the Makefiles). 

As soon as i get my hands on a 3.16 install i can test stuff, but time is rare :)

**Comment by loctauxphilippe** [comment]
@cldx When 3.16 is out on Fedora, I'll test them for you!

**Comment by cldx** [comment]
@loctauxphilippe yep, that's about the same time i can work on it too. Fedora FTW :)

**Comment by loctauxphilippe** [comment]
@cldx I have the ISO of Fedora 22 alpha with Gnome 3.15.9. I'll wait until 3.16 to test

**Comment by me4oslav** [comment]
On the bright side I don't think there are dock API changes from 3.14 to 3.16, so porting this on theory should be just a metadata.json file.

**Comment by marko-lazic** [comment]
@me4oslav That is what i needed to know. Thank you.

**Comment by marko-lazic** [comment]
I added 3.15.91 to metadata.json and it works. I wonder if you guys would mind me requesting merge for that number to official metadata.json?

**Comment by tomvanderlee** [comment]
Probably not, because 3.15.9 is an beta. We only support official releases. If you are advanced enough to run beta software, you are advanced enough to edit the metadata.json file.

**Comment by cldx** [comment]
Just fyi, the Metadata was updated to 3.16 in the repo.

For everybody running some development version of GS, just update your metadata.json file with your current GS Version number, you can always check it with running 'gnome-shell --version'. 

Closing this then.
