### ISSUE TITLE
How to remove Atom-Dock

### ISSUE THREAD

**Issue by furusiyya** [ozonos/atom-dock#64]
I used **sudo make uninstall** but I got no success. So please do mention a systematic way to uninstall this

**Comment by mpnordland** [comment]
There wasn't a way IIRC. Just go into /usr/share/gnome-shell/extensions/ and delete the extension directory. That will remove it.

On February 10, 2016 8:59:53 AM EST, MohammadBilalArif notifications@github.com wrote:

> I used **sudo make uninstall** but I got no success. So please do
> mention a systematic way to uninstall this
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ozonos/atom-dock/issues/64

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Atracelex** [comment]
@mpnordland thanks for the answer, that actually worked (:

**Comment by furusiyya** [comment]
Thanks @mpnordland
